# Page settings
baseurl = "localhost:1313"
title = "Ikshana"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "IKSHANA"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Ikshana"
    subtitle = "Building Dreams"
    logo = "logo-white-final.png"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Planning is having a vision for future and or foresight. A well planned project can be executed within schedule, within budget, as per the scope, in desired quality and to clients satisfaction. So as civil engineers, we always plan first."
    url = "contact"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "We employ novel methods in the design of buildings and architectural design, based, mainly, on the technological development in construction materials used and the reliance on environmental-friendly and stronger materials. Thereby, delivering a truly refined product."
    url = "services"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Build"
    description = "Our motto is 'Building Dreams'. We understand your needs, design it to the required specifications and build it to your dreams so that your faith in us stands strong like our structures. Of the many things that we build, trust is most important."
    url = "testimonials"
    button = "Why us?"
    icon = "icon-building"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "In the past, our projects have been taken from a wide range of specializations, dealing with varied domains across civil engineering."
    footertext = ''

    [[params.work.row]]
      img = "project.png"
      alt = "Image2"
      title = "IIT Kharagpur Railover Bridge"
      subtitle = "The Railway Over Bridge at Kharagpur Junction is of great importance for the people of Kharagpur. The main purpose for the construction of the rail over bridge was to reduce the traveling time of road traffic and avoiding accidents during passing of trains. The construction of the bridge began in March, 2015 and was delivered efficiently by November, 2017 at a cost of ₹1.2B (16.34M $). The bridge today serves its most basic purpose of fulfilling more than 10,000 vehicles per day."

    [[params.work.row]]
      img = "project2.png"
      alt = "Image2"
      title = "Nalanda Greater Track"
      subtitle = "Kharagpur serves a major junction for road vehicles to navigate to major cities of India, namely, Mumbai and Kolkata. Ikshana has had the privilege of joining hands with Larsen and Toubro for the construction of the largest rotary in India at Kharagpur by-pass for controlling heavy traffic. The project is today used by more than 1Lac vehicles on daily purpose, most of which are heavy vehicles like trucks, buses, etc. The project costed ₹3B ($40.8M) and was delivered in 2 Years(2017-2019)."

    [[params.work.row]]
      img = "project3.png"
      alt = "Image3"
      title = "Hijli Railway Track"
      subtitle = "The project involved the construction of 120km of new standard-gauge Single Track Electrified Railway Line between Hijli and Kolkata. The total cost of the Project was ₹1.5B ($20.4M). The immediate impact of the project was promoting economic development in the region by significantly increasing employment. In the operation stage we paid special attention to the environment and we proudly declare that no wildlife reserve was disrupted during or after the construction of the project."

    [[params.work.row]]
      img = "project4.png"
      alt = "Image4"
      title = "Tehri multi-purpose dam"
      subtitle = "Tehri Multi-Purpose Dam has been built over river Bhagirathi in near Tehri, Uttrakhand. The dam serves many purposes such as controlling flow of water, canaling sufficient fresh water for majorly irrigation purposes in parts of Uttarakhand and Uttar Pradesh and for producing hydro-electricity. The dam, in collaboration with Hindustan Construction Co. Ltd. built at an extreme location was completed in 5 Years and at a cost of ₹7.4B ($100.8M). Today, the project is helping more than 5 crore Indians in their daily needs."

    [[params.work.row]]
      img = "project5.png"
      alt = "Image5"
      title = "Water Section Bore Well, IIT Kharagpur"
      subtitle = "Our 1st major project was the Water Section Bore Well, at IIT Kharagpur. IIT Kharagpur, being home to almost 25,000 people, has enough water requirements. The bore well constructed was dug 45m below the ground level. A strong support and proper design with state of the art machinery was provided to counter the normal forces through the soil. The cost for the project was ₹25 crores ($3.4M) and was completed in a span of 8 months. The borewell today provides 1Lac Litres of water to the campus essentials everyday. "

    [[params.work.row]]
      img = "project6.png"
      alt = "Image6"
      title = "Lakeside Levee, IIT Kharagpur"
      subtitle = "Lakeside Levee was Ikshana’s one of the major projects in IIT Kharagpur. Ikshana has taken pride in providing its service for developing beautiful Lakeside Structures inside the campus for 3 lakes. A Levee gives a firm support to the banks of any water body, abling it for more developments around it. The idea consisted of developing a presentable Lakeside along with strength. The project costed ₹1.2B ($16.34M) and was completed in a span of 2 Years. The hence developed Lakeside is a famous spot for students to hang-out. "

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "This is what our customers had to say about us."

    [[params.testimonials.item]]
      quote = "&ldquo;Our experience with Ikshana was marked by high integrity, good quality, and high value work. Thank you for the amazing job on our new clinic.We couldn't have asked for a better team to produce a high quality product you have done.&rdquo;"
      person = 'Dr. Keyur Parikh, Chairman, CIMS Hospital Pvt. Ltd'
      img = "user.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Ikshana has provided excellent service and quality during the past year. Completing the work  on time, and within budget,is an extremely important component in development of commercial buildings. Ikshana has played an important role in this process. We will highly recommend  for the type of work you performed for us.&rdquo;"
      person = 'Dr. Bimal Patel, Director, HCP Design, Planning &amp; Management Pvt. Ltd'
      img = "user.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;IKSHANA Kolkata, has executed the construction work of our Institute Kolkata. IKSHANA is professionally managed organization and their performance has been good in terms of quality, safety and timely completion of the project.&rdquo;"
      person = 'Dr. Parth Kumar Tewari, Director, ICE Kolkata'
      img = "user.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "With a dedicated team of trained professionals, we strive to create new engineering marvels by providing novel and innovative solutions. "

    [[params.services.item]]
      title = "Our Vision"
      description = "As our name suggests, we are a group of visionary people. Dreaming and achieving is our primary goal. Ikshana has worked over major projects to make somebody’s dream come true. We believe in deliverance rather than bragging, and that’s why our competitors only keep completing banners, and we, buildings."
      icon = "icon-eye"

    [[params.services.item]]
      title = "Preeminent Technology"
      description = "Ikshana uses highly advanced Technology to analyze, design and build a project. As the time is passing, the technology is improving and we at Ikshana, are ready to learn those advancements to deliver, not a complete project but a flawless masterpiece. Deep Learning and Artificial Intelligence are some topics which we actually use in our project and not only in the description."
      icon = "icon-gear"
    [[params.services.item]]
      title = "Conservationist"
      description = "Our nature is definitely ours. And its protection and growth lies in our hands. We at Ikshana don’t build the technology which protects the environment, rather, we build the technology through which the environment does not require any protection. Even we admire the beauty of fresh trees on a sunny winter morning! "
      icon = "icon-leaf"

      [[params.services.item]]
      title = "Erudite Team"
      description = "Our team consists of top Civil Engineers from IITs to serve their country. We all know how brainy these people are! Our team works restlessly(which they are used to), to analyze each and every bit of a design so that you don’t feel a sudden jerk when you are driving while listening to your favorite song!   " 
      icon = "icon-people"

  # About section

  
  [params.about]
    enable = true
    title = "About"
    description = "Meet our team: A group of enthusiastic individuals working in extraordinary projects."

    [[params.about.item]]
      name = "Mahendra Bera"
      position = "Chief Executive Officer"
      description = "Mahendra Bera is serving as the current Chief Executive Officer of Ikshana. He supritends the smooth functioning of all departments. Standing very true to his position, he acts like an epoxy, filling all the gaps and strengthening the entire team together! He has a deep rooted knowledge of the overall markets and the general industry of the company."
      img = "Mahendra_Bera.jpg"
      alt = "Person3"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/mahendra-bera-a12b711b8"],
        ["icon-facebook", "http://www.facebook.com/mahendra.bera.52438"],
        ["icon-envelope", "mailto: mahendrabera507@gmail.com "]
      ]   

    [[params.about.item]]
      name = "Rahul Gorai"
      position = "Chief Technology Officer"
      description = "As a Chief Technological Officer, Rahul Gorai is responsible for developing the company’s strategy for using technological resources. He is mainly responsible for the mangement of company's websites, development of app for our latest project and the algorithm behind it. He ensures that technologies are used efficiently and profitably."
      img = "Rahul_Gorai.jpg"
      alt = "Person2"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/rahul-gorai-86a7041a2/"],
        ["icon-facebook", "https://www.facebook.com/rahul.gorai.526/"],
        ["icon-github", "https://github.com/sudo-rgorai"]
      ]

    [[params.about.item]]
      name = "Samarth Saxena"
      position = "Chief Technology Officer"
      description = "Samarth Saxena, our Chief Technology Officer is responsible for the oversight of intellectual property and have backgrounds in the industry. He looks at how to implement new technologies within the company to its success. He along with his collegue is responsible for the development of the website and also looks after data security."
      img = "Samarth_Saxena.jpg"
      alt = "Person3"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/samarth-saxena-265260128/"],
        ["icon-facebook", "https://www.facebook.com/samarth.saxena.906/"],
        ["icon-envelope", "mailto: samsaxena835@gmail.com"]
      ]   
      
    [[params.about.item]]
      name = "Hritwick Manna"
      position = "Chief Financial Officer"
      description = "As chief financial officer (CFO), Hritwick Manna is responsible for all of the company’s financial functions including accounting, audit, treasury, corporate finance and investor relations. He also leads the AI team. He drives the company’s financial planning and performs risk management by analyzing the organization’s liabilities and investments."
      img = "Hritwick_Manna.jpg"
      alt = "Person3"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/hritwickmanna"],
        ["icon-facebook", "https://www.facebook.com/hritwickm"],
        ["icon-envelope", "mailto: hritwick.manna24@gmail.com"]
      ]

    [[params.about.item]]
      name = "Mihir Kumar Choudhury"
      position = "Director, Research & Development"
      description = "Mihir Kumar Choudhury, Director of Research and Development,is a new rising face in the corporate world. He is known to be a visionary personality with optimistic ideals who believes in dreams and turn them into reality. He has always worked for the holistic development of Ikshana"
      img = "Mihir.jpg"
      alt = "Person1"
      social = [
        ["icon-linkedin", "http://www.linkedin.com/in/mihirkc"],
        ["icon-facebook", "https://www.facebook.com/mihirkumar.choudhury.3"],
        ["icon-envelope", "mailto: mihirkumarchoudhury@gmail.com"]
      ]

    [[params.about.item]]
      name = "Ayan Akhtar"
      position = "Chief Financial Officer"
      description = "Ayan Akhtar is serving as the Chief Financial Officer. He is responsible for all of the company's financial function. He decides on investment strategies by considering cash and liquidity risks and controls and evaluate the organization’s fundraising plans and capital structure. He also ensures cash flow is appropriate for the organization’s operations."
      img = "Ayan_Akhtar.jpg"
      alt = "Person3"
      social = [
        ["icon-linkedin", "http://www.linkedin.com/in/ayan-akhtar-87b8191b9"],
        ["icon-facebook", "http://facebook.com/being.ayan.54"],
        ["icon-envelope", "rehanayan785@gmail.com"]
      ]   

    [[params.about.item]]
      name = "Tuhin Subhra De"
      position = "Director, Research & Development"
      description = "Tuhin Subhra De, dynamically focuses on areas of research and development which will prove beneficial for company and keep it in good market conditions and in competition with other companies."
      img = "Tuhin_Subhra_De.jpg"
      alt = "Person3"
      social = [
        ["icon-linkedin", "https://in.linkedin.com/in/tuhin-subhra-de-2a83721b5"],
        ["icon-facebook", "https://www.facebook.com/tuhinsubhrade.1107"],
        ["icon-envelope", "mailto: tuhinsubhrade069@gmail.com "]
      ]   

    [[params.about.item]]
      name = "Punith Srikanth"
      position = "Director, Marketing"
      description = "Titty Punith Srikanth, our Director of Marketing is responsible for our company's Marketing and communication strategies,  as well as overall branding and image. He prepares annual marketing plans and sets the overall marketing budget"
      img = "Punith_Srikant.jpg"
      alt = "Person3"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/titty-srikanth-31978b1b7"],
        ["icon-facebook", "https://www.facebook.com/tpunith.srikanth"],
        ["icon-envelope", "mailto: tittysrikanth2002@gmail.com "]
      ]   

    [[params.about.item]]
      name = "Paul Manohar"
      position = "Director, Legal Affairs"
      description = "As director of legal affairs, Paul Manohar provides legal representation to the Organization, supports the work of the organization and manages the full range of legal strategies and responsibilities. He also develops and manages the legal department budget"
      img = "Pusuluri_Paul_Manohar.jpg"
      alt = "Person3"
      social = [
        ["icon-linkedin", "#"],
        ["icon-facebook", "#"],
        ["icon-envelope", "#"]
      ]   

    [[params.about.item]]
      name = "Aman Saxena"
      position = "Director, Marketing"
      description = "Aman Saxena, our Director of Marketing is responsible for our company’s marketing strategies. He has a very good grip among his clients. The market and demand analysis provided by him is of great importance to the welfare of the company. He leads complex legal projects that span legal, business, and functional boundaries and provides counsel to staff in all departments on a variety of complex issues."
      img = "user.jpg"
      alt = "Person3"
      social = [
        ["icon-linkedin", "#"],
        ["icon-facebook", "#"],
        ["icon-envelope", "#"]
      ]           

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Years of trust"
      icon = "icon-calendar"
      from = 0
      to = 15
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000


    [[params.counters.item]]
      description = "Partners"
      icon = "icon-globe"
      from = 0
      to = 36
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 878
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "We'd love to hear from you. Whether you have a question about our projects, pricing, practices or anything else our team is ready to answer all your questions."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Indian Institute of Technology Kharagpur, Kharagpur - 721302, West Bengal, India"],
        ["icon-phone", "+91 7550912254"],
        ["icon-envelope", "ikshana004@gmail.com"],
        ["icon-globe", '<a href="http://ikshana.netlify.app/" target="_blank">http://ikshana.netlify.app/</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Ikshana. All Rights Reserved. <br>Created with <a href="http://gohugo.io/" target="_blank">hugo</a>.'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-linkedin", "#linkedin"]
      ] 
